name: trainingpipeline
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2026.1.4=h4c7d964_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - liblzma=5.8.1=h2466b09_2
  - libsqlite=3.51.2=hf5d6505_0
  - libzlib=1.3.1=h2466b09_2
  - openssl=3.6.0=h725018a_0
  - pip=25.3=pyh8b19718_0
  - python=3.10.19=hc20f281_2_cpython
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=h2c6b04d_3
  - tzdata=2025c=hc9c84f9_1
  - ucrt=10.0.26100.0=h57928b3_0
  - vc=14.3=h41ae7f8_34
  - vc14_runtime=14.44.35208=h818238b_34
  - vcomp14=14.44.35208=h818238b_34
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - absl-py==2.3.1
      - astunparse==1.6.3
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - decord==0.6.0
      - einops==0.8.1
      - filelock==3.20.0
      - flatbuffers==25.12.19
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - ftfy==6.3.1
      - gast==0.7.0
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - idna==3.11
      - iopath==0.1.10
      - jinja2==3.1.6
      - keras==3.12.0
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - mpmath==1.3.0
      - namex==0.1.0
      - networkx==3.4.2
      - numpy==2.1.3
      - onnx==1.16.1
      - onnx-graphsurgeon==0.5.8
      - onnx2tf==1.22.0
      - onnxruntime==1.23.2
      - onnxruntime-gpu==1.23.2
      - onnxslim==0.1.82
      - opencv-python==4.12.0.88
      - opt-einsum==3.4.0
      - optree==0.18.0
      - packaging==25.0
      - pillow==12.0.0
      - pillow-heif==1.1.1
      - polars==1.37.1
      - polars-runtime-32==1.37.1
      - portalocker==3.2.0
      - protobuf==5.29.5
      - psutil==7.2.1
      - pycocotools==2.0.11
      - pygments==2.19.2
      - pyparsing==3.3.1
      - pyreadline3==3.5.4
      - python-dateutil==2.9.0.post0
      - pywin32==311
      - pyyaml==6.0.3
      - regex==2026.1.15
      - requests==2.32.5
      - rich==14.2.0
      - safetensors==0.7.0
      - sam3==0.1.2
      - scipy==1.15.3
      - six==1.17.0
      - sng4onnx==1.0.1
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.1
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.3.0
      - tf-keras==2.19.0
      - timm==1.0.24
      - torch==2.6.0+cu124
      - torchaudio==2.6.0+cu124
      - torchvision==0.21.0+cu124
      - tqdm==4.67.1
      - triton==3.1.0
      - typing-extensions==4.15.0
      - ultralytics==8.4.3
      - ultralytics-thop==2.0.18
      - urllib3==2.6.3
      - wcwidth==0.2.14
      - werkzeug==3.1.5
      - wrapt==2.0.1
